version: "3.9"
name: TestAgent
services:
  webapi:
    image: webapi-image:latest
    build:
      context: ./backend/WebApplication1
      dockerfile: Dockerfile
    container_name: webapi
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  react:
    image: react-image:latest
    build:
        context: ./frontend/ReactApp
        dockerfile: Dockerfile
    container_name: react
    ports:
      - "50001:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production