name: TestAgent
services:
  webapi:
    build:
      context: ./backend/WebApplication1
      dockerfile: Dockerfile
    image: webapi-image:latest
    container_name: webapi
    ports:
      - "50000:50000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always

  react:
    build:
      context: ./frontend/ReactApp
      dockerfile: Dockerfile
    image: react-image:latest
    container_name: react
    ports:
      - "50001:80"    
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always

    my-portal:
    build:
      context: ./frontend/my-portal
      dockerfile: Dockerfile
    image: my-portal:latest
    container_name: my-portal
    ports:
      - "60000:60000"    
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf