name: TestAgent
services:
  webapi:
    build:
      context: ./backend/WebApplication1
      dockerfile: Dockerfile
      args:
        GIT_TAG: ${GIT_TAG}
    image: webapi-image:${GIT_TAG}
    container_name: webapi
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  
  react:
    build:
        context: ./frontend/ReactApp
        dockerfile: Dockerfile
        args:
          GIT_TAG: ${GIT_TAG}
    image: react-image:${GIT_TAG}
    container_name: react
    ports:
      - "50001:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production