name: TestAgent
services:
  networks:
    my-network:
      driver: bridge
      external: true
  webapi:
    build:
      context: ./backend/WebApplication1
      dockerfile: Dockerfile
    image: webapi-image:latest
    container_name: webapi
    ports:
      - "5000:5000"
    networks:
      - my-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always

  react:
    build:
      context: ./frontend/ReactApp
      dockerfile: Dockerfile
    image: react-image:latest
    container_name: react
    ports:
      - "50001:80"    
    networks:
      - my-network
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always

