# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: self-hosted
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
      # - uses: actions/checkout@v4
      # - name: Setup .NET 8.x
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     # Semantic version range syntax or exact version of a dotnet version
      #     dotnet-version: '8.x'
          
      # # You can test your matrix by printing the current dotnet version
      # - name: Display dotnet version
      #   run: dotnet --version
      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - run: dotnet publish backend/WebApplication1 -c Release -o /home/doradora/app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
        working-directory: frontend/ReactApp
      - run: npm run build
        working-directory: frontend/ReactApp
      - run: ls -R frontend/ReactApp/dist
      - uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: frontend/ReactApp/dist/

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./react-artifact
      - run: sudo cp -r react-artifact/* /var/www/react-app/



      
      # - name: Start web app
      #   run : ./publish/WebApplication1
      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo ${{ secrets.PS }} | sudo -S reboot

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
