# This is a basic workflow to help you get started with Actions

name: For native app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dotnet-build-in-self-hosted:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '8.x'
          
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Release build and publish
        run: dotnet publish backend/WebApplication1 -c Release -o /home/doradora/app
    # The type of runner that the job will run on
    
  react-build-in-ubuntsu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: frontend/ReactApp
      - name: Build
        run: npm run build
        working-directory: frontend/ReactApp
      - name: Display built files
        run: ls -R frontend/ReactApp/dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: frontend/ReactApp/dist/

  deploy:
    needs: react-build-in-ubuntsu-latest
    runs-on: self-hosted
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./react-artifact
      - name: Deploy new artifacts to Nginx
        run: echo "${{ secrets.RUNNER_PASSWORD }}" | sudo -S cp -r react-artifact/* /var/www/react-app/
      




