name: For docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main", "development"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-self-hosted:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  git-version:
    runs-on: doradora-windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Git Version
        shell: bash
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Debug Version
        run: echo "Tag:${{ env.Tag }}"
      - name: Debug Environment Variables
        run: echo "GIT_TAG=${{ env.tag }}"
        
  build-in-self-hosted:
    runs-on: self-hosted
    steps:
      - name: Build 
        run: |
          echo "${{ secrets.RUNNER_PASSWORD }}" | sudo -S docker compose build --build-arg GIT_TAG=${{ env.tag }}
      - name: Deploy with Docker Compose
        run: |
          echo "${{ secrets.RUNNER_PASSWORD }}" | sudo -S docker compose up -d
